global:
  scrape_interval: 5s  # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s  # By default, scrape targets every 15 seconds.
  external_labels:
    cluster: 'cluster-b'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'sample-metrics-cluster'
    static_configs:
      - targets:
          - 'host.docker.internal:8081'

  - job_name: 'promxy'
    static_configs:
      - targets:
          - 'host.docker.internal:8082'

